server:
  port: 8081

spring:
  application:
    name: student-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/student?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: pass@word1
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        generate_statistics: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
